name: 功能建议（中文）
description: 提交新能力或改进建议
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        请先描述问题背景，再说明方案与可验收标准。
  - type: textarea
    id: problem
    attributes:
      label: 问题背景
      description: 你想解决什么用户问题或工程痛点？
      placeholder: 当前无法...导致...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 方案描述
      description: 请描述预期行为以及 API/交互变化。
      placeholder: 建议增加...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 你考虑过哪些替代方案，为什么不采用？
  - type: dropdown
    id: scope
    attributes:
      label: 变更规模
      options:
        - 小（单文件或低风险）
        - 中（多模块或中等风险）
        - 大（架构或协议层影响）
    validations:
      required: true
  - type: checkboxes
    id: affected-modules
    attributes:
      label: 影响模块
      options:
        - label: 路由层（`src/routes/*`）
        - label: 中间件层（`src/middleware/*`）
        - label: 配置层（`src/config/*`）
        - label: 日志系统（`src/Logger.ts`）
        - label: 启动运行层（`src/app.ts`, `src/server.ts`）
        - label: 文档
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 验收标准
      description: 请列出可验证的完成标准。
      placeholder: |
        - [ ] 接口返回...
        - [ ] 保持向后兼容
        - [ ] 文档已更新
    validations:
      required: true
  - type: textarea
    id: compatibility
    attributes:
      label: 兼容性与破坏性变更
      description: 对已有接口、客户端或部署的影响。
      placeholder: 无影响 / 需要迁移说明...
  - type: textarea
    id: extra
    attributes:
      label: 补充信息
      description: 关联 issue、参考资料、基准数据或原型链接。
  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前确认
      options:
        - label: 我已检索现有 issue，确认不是重复需求。
          required: true
        - label: 我已给出明确可验证的验收标准。
          required: true
